<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/master/M2C1%20NumPy_Foundations_Student_Colab_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numerical Computing with NumPy

## Beginner-Friendly, Industry-Relevant Foundation Notebook

This notebook is aligned with the instructor micro-level LO document. It focuses only on must-have NumPy foundations needed for data analysis, ML preparation, Pandas, and Scikit-learn workflows.

**Audience note:** This notebook assumes learners may be new to programming. Each section starts with a practical reason, followed by simple executable examples.


## Session Learning Outcomes

By the end of this notebook, learners should be able to:

1. Explain why NumPy is useful for numerical computing.
2. Create 1D and 2D NumPy arrays.
3. Inspect arrays using `ndim`, `shape`, `size`, and `dtype`.
4. Select data using indexing, slicing, and boolean filtering.
5. Perform vectorized numerical operations without writing manual loops.
6. Use common mathematical and statistical functions.
7. Reshape and flatten arrays for simple data preparation.
8. Complete a small industry-style numerical workflow.


## 1. Why NumPy? Numerical Computing Mindset

In real-world data work, we often need to perform the same operation on many numbers:

- Add bonus marks to all students
- Apply GST/tax to all product prices
- Convert temperatures for many sensor readings
- Calculate revenue from price and quantity

Plain Python lists are useful, but NumPy makes numerical operations faster and cleaner.


In [ ]:
# Import NumPy using the standard industry convention
import numpy as np

print('NumPy imported successfully!')
print('NumPy version:', np.__version__)

NumPy imported successfully!
NumPy version: 2.0.2


In [ ]:
# Python list approach: add 5 bonus marks to each student
marks_list = [45, 67, 82, 39, 90]

bonus_marks_list = []
for mark in marks_list:
    bonus_marks_list.append(mark + 5)

print('Original marks using Python list:', marks_list)
print('After adding bonus using loop:', bonus_marks_list)

Original marks using Python list: [45, 67, 82, 39, 90]
After adding bonus using loop: [50, 72, 87, 44, 95]


In [ ]:
# NumPy vectorized approach: add 5 bonus marks to each student
marks_array = np.array([45, 67, 82, 39, 90])
bonus_marks_array = marks_array + 5

print('Original marks using NumPy array:', marks_array)
print('After adding bonus using NumPy:', bonus_marks_array)

Original marks using NumPy array: [45 67 82 39 90]
After adding bonus using NumPy: [50 72 87 44 95]


> **Key idea:** Vectorization means applying an operation to many values at once without writing a manual loop.


## 2. Creating NumPy Arrays from Real-Looking Data

A NumPy array is like a container for numbers. It can represent:

- A single list of values: 1D array
- A table of rows and columns: 2D array


In [ ]:
# 1D array: marks of five students
student_marks = np.array([72, 85, 64, 90, 58])
print(student_marks)

[72 85 64 90 58]


In [ ]:
# 2D array: rows are students, columns are subjects
# Columns: Python, Math, Communication
score_table = np.array([
    [72, 80, 75],
    [85, 78, 82],
    [64, 70, 68],
    [90, 88, 92],
    [58, 60, 62]
])

print(score_table)

[[72 80 75]
 [85 78 82]
 [64 70 68]
 [90 88 92]
 [58 60 62]]


### Common Array Creation Functions

These are frequently used in data analysis, ML, and testing code examples.


In [ ]:
# Create arrays filled with zeros and ones
zeros_array = np.zeros(5)
ones_array = np.ones(5)

print('Zeros:', zeros_array)
print('Ones:', ones_array)

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]


In [ ]:
# Create a sequence using arange
# Similar to Python range, but returns a NumPy array
numbers = np.arange(1, 11)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Create equally spaced numbers using linspace
# Useful when dividing a range into equal parts
points = np.linspace(0, 1, 5)
print(points)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create repeatable random data for classroom demos
np.random.seed(42)
random_marks = np.random.randint(35, 101, size=10)
print(random_marks)

[86 49 95 55 58 37 56 87 36 64]


### Quick Practice 1
Create a NumPy array called `prices` with five product prices: 100, 250, 75, 300, 150.


In [ ]:
# Practice 1 - Try it yourself
prices = np.array([100, 250, 75, 300, 150])
print(prices)

[100 250  75 300 150]


## 3. Inspecting Arrays: Shape, Dimension, Size, and Data Type

Before working with data, we should first understand its structure.

This is similar to checking a spreadsheet before applying formulas.


In [ ]:
print('Score table:')
print(score_table)

print('\nNumber of dimensions:', score_table.ndim)
print('Shape:', score_table.shape)
print('Total number of values:', score_table.size)
print('Data type:', score_table.dtype)

Score table:
[[72 80 75]
 [85 78 82]
 [64 70 68]
 [90 88 92]
 [58 60 62]]

Number of dimensions: 2
Shape: (5, 3)
Total number of values: 15
Data type: int64


### Understanding Shape

For `score_table.shape`, output `(5, 3)` means:

- 5 rows: 5 students
- 3 columns: 3 subjects


In [ ]:
rows, columns = score_table.shape
print('Number of students:', rows)
print('Number of subjects:', columns)

Number of students: 5
Number of subjects: 3


### Quick Practice 2
Inspect the `prices` array created earlier using `ndim`, `shape`, `size`, and `dtype`.


In [ ]:
print('Prices:', prices)
print('Dimensions:', prices.ndim)
print('Shape:', prices.shape)
print('Size:', prices.size)
print('Data type:', prices.dtype)

Prices: [100 250  75 300 150]
Dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


## 4. Selecting Data: Indexing, Slicing, and Filtering

In real-world work, we rarely use all data at once. We often need to select specific values, rows, columns, or values that match a condition.


### 4.1 Indexing in 1D Arrays

Index positions start from 0.


In [ ]:
marks = np.array([72, 85, 64, 90, 58])

print('All marks:', marks)
print('First student mark:', marks[0])
print('Third student mark:', marks[2])
print('Last student mark:', marks[-1])

All marks: [72 85 64 90 58]
First student mark: 72
Third student mark: 64
Last student mark: 58


### 4.2 Slicing in 1D Arrays

Slicing selects a range of values.


In [ ]:
print('First three marks:', marks[0:3])
print('Marks from index 2 onwards:', marks[2:])
print('Marks except last value:', marks[:-1])

First three marks: [72 85 64]
Marks from index 2 onwards: [64 90 58]
Marks except last value: [72 85 64 90]


### 4.3 Indexing in 2D Arrays

For 2D arrays, use `[row, column]`.


In [ ]:
print(score_table)

print('\nFirst student, Python score:', score_table[0, 0])
print('Fourth student, Communication score:', score_table[3, 2])

[[72 80 75]
 [85 78 82]
 [64 70 68]
 [90 88 92]
 [58 60 62]]

First student, Python score: 72
Fourth student, Communication score: 92


### 4.4 Selecting Rows and Columns


In [ ]:
# Select complete row: all subject scores of first student
print('First student all scores:', score_table[0, :])

# Select complete column: Python scores of all students
print('Python scores of all students:', score_table[:, 0])

# Select Math scores of all students
print('Math scores of all students:', score_table[:, 1])

First student all scores: [72 80 75]
Python scores of all students: [72 85 64 90 58]
Math scores of all students: [80 78 70 88 60]


### 4.5 Boolean Filtering

Boolean filtering helps us select values that satisfy a condition.


In [ ]:
marks = np.array([72, 85, 64, 90, 58, 33, 49])

pass_mask = marks >= 50
print('Marks:', marks)
print('Pass mask:', pass_mask)
print('Passing marks only:', marks[pass_mask])

Marks: [72 85 64 90 58 33 49]
Pass mask: [ True  True  True  True  True False False]
Passing marks only: [72 85 64 90 58]


In [ ]:
# Same filtering in one line
passing_marks = marks[marks >= 50]
failed_marks = marks[marks < 50]

print('Passing marks:', passing_marks)
print('Failed marks:', failed_marks)

Passing marks: [72 85 64 90 58]
Failed marks: [33 49]


### Quick Practice 3
From the `prices` array, select products priced above 150.


In [ ]:
prices_above_150 = prices[prices > 150]
print('Prices above 150:', prices_above_150)

Prices above 150: [250 300]


## 5. Vectorized Operations: Replacing Loops with Array Operations

Vectorization is one of the most important NumPy concepts.

It helps us write shorter and cleaner code for numerical operations.


### 5.1 Array-to-Scalar Operations

Apply one number to every value in the array.


In [ ]:
marks = np.array([72, 85, 64, 90, 58])

print('Original marks:', marks)
print('After adding 5 bonus marks:', marks + 5)
print('After doubling marks:', marks * 2)
print('Marks as percentage of 100:', marks / 100)

Original marks: [72 85 64 90 58]
After adding 5 bonus marks: [77 90 69 95 63]
After doubling marks: [144 170 128 180 116]
Marks as percentage of 100: [0.72 0.85 0.64 0.9  0.58]


### 5.2 Array-to-Array Operations

When two arrays have matching positions, NumPy can operate element by element.


In [ ]:
prices = np.array([100, 250, 75, 300, 150])
quantities = np.array([2, 1, 5, 1, 3])

revenue = prices * quantities

print('Prices:', prices)
print('Quantities:', quantities)
print('Revenue per product:', revenue)

Prices: [100 250  75 300 150]
Quantities: [2 1 5 1 3]
Revenue per product: [200 250 375 300 450]


### 5.3 Business Rule Example: Apply GST/Tax


In [ ]:
prices = np.array([100, 250, 75, 300, 150])
gst_rate = 0.18

final_prices = prices + (prices * gst_rate)

print('Original prices:', prices)
print('Final prices after 18% GST:', final_prices)

### 5.4 Using `np.where` for Simple Conditions

`np.where(condition, value_if_true, value_if_false)` is useful for simple classification or transformation.


In [ ]:
marks = np.array([72, 85, 64, 90, 58, 33, 49])

result = np.where(marks >= 50, 'Pass', 'Fail')

print('Marks:', marks)
print('Result:', result)

In [ ]:
# Add 5 bonus marks, but cap the maximum score at 100
marks = np.array([96, 82, 77, 99, 65])
bonus_marks = marks + 5
capped_marks = np.where(bonus_marks > 100, 100, bonus_marks)

print('Original marks:', marks)
print('After bonus:', bonus_marks)
print('After capping at 100:', capped_marks)

### Quick Practice 4
Given product prices, apply a 10% discount using vectorization.


In [ ]:
prices = np.array([100, 250, 75, 300, 150])
discounted_prices = prices - (prices * 0.10)

print('Original prices:', prices)
print('Discounted prices:', discounted_prices)

## 6. Useful Mathematical and Statistical Functions

NumPy provides ready-made functions to summarize numerical data.


In [ ]:
marks = np.array([72, 85, 64, 90, 58, 33, 49])

print('Marks:', marks)
print('Total:', np.sum(marks))
print('Average:', np.mean(marks))
print('Minimum:', np.min(marks))
print('Maximum:', np.max(marks))
print('Median:', np.median(marks))
print('Standard deviation:', np.std(marks))
print('Rounded standard deviation:', np.round(np.std(marks), 2))

### Axis-Based Operations

For 2D arrays:

- `axis=0` means column-wise calculation
- `axis=1` means row-wise calculation


In [ ]:
# Rows: students
# Columns: Python, Math, Communication
score_table = np.array([
    [72, 80, 75],
    [85, 78, 82],
    [64, 70, 68],
    [90, 88, 92],
    [58, 60, 62]
])

print(score_table)

In [ ]:
student_averages = np.mean(score_table, axis=1)
subject_averages = np.mean(score_table, axis=0)

print('Average score per student:', student_averages)
print('Average score per subject:', subject_averages)

In [ ]:
subject_names = np.array(['Python', 'Math', 'Communication'])

for subject, avg in zip(subject_names, subject_averages):
    print(subject, 'average =', round(avg, 2))

### Quick Practice 5
Calculate total revenue and average revenue from the `revenue` array.


In [ ]:
prices = np.array([100, 250, 75, 300, 150])
quantities = np.array([2, 1, 5, 1, 3])
revenue = prices * quantities

print('Revenue per product:', revenue)
print('Total revenue:', np.sum(revenue))
print('Average revenue:', np.mean(revenue))

## 7. Reshaping Data for Analysis and ML Readiness

Sometimes raw data comes as a single sequence, but we need to arrange it as rows and columns.

Important rule: The total number of values must remain the same.


In [ ]:
monthly_sales = np.array([120, 135, 150, 160, 170, 165, 180, 190, 200, 210, 220, 230])

print('Monthly sales as 1D array:')
print(monthly_sales)
print('Shape:', monthly_sales.shape)

In [ ]:
# Reshape 12 monthly values into 4 quarters x 3 months
quarterly_sales = monthly_sales.reshape(4, 3)

print('Quarterly sales table:')
print(quarterly_sales)
print('Shape:', quarterly_sales.shape)

In [ ]:
# Flatten a 2D array back to 1D
flattened_sales = quarterly_sales.flatten()

print('Flattened sales:')
print(flattened_sales)
print('Shape:', flattened_sales.shape)

### Common Reshape Error

The following example is intentionally shown with error handling.

We cannot reshape 12 values into 5 rows and 3 columns because 5 × 3 = 15 values are required.


In [ ]:
try:
    wrong_shape = monthly_sales.reshape(5, 3)
except ValueError as error:
    print('Error message:', error)
    print('Reason: 12 values cannot fit into a 5 x 3 table.')

### Quick Practice 6
Create numbers from 1 to 12 and reshape them into a 3 x 4 table.


In [ ]:
numbers = np.arange(1, 13)
table_3_by_4 = numbers.reshape(3, 4)

print(table_3_by_4)

## 8. Mini Industry-Style Practice: Product Sales Analysis

In this mini case study, we will combine the must-have NumPy concepts:

- Array creation
- Inspection
- Vectorized revenue calculation
- Filtering
- Aggregation
- Plain-English interpretation


In [ ]:
# Product sales data
product_names = np.array(['Notebook', 'Pen', 'Bag', 'Bottle', 'Calculator'])
prices = np.array([80, 10, 600, 250, 450])
quantities_sold = np.array([120, 500, 35, 80, 45])

print('Products:', product_names)
print('Prices:', prices)
print('Quantities sold:', quantities_sold)

In [ ]:
# Step 1: Inspect arrays
print('Product names shape:', product_names.shape)
print('Prices shape:', prices.shape)
print('Quantities shape:', quantities_sold.shape)

In [ ]:
# Step 2: Calculate revenue using vectorization
revenue = prices * quantities_sold

print('Revenue per product:', revenue)

In [ ]:
# Step 3: Show revenue with product names
for product, rev in zip(product_names, revenue):
    print(product, 'revenue = Rs.', rev)

In [ ]:
# Step 4: Calculate total and average revenue
total_revenue = np.sum(revenue)
average_revenue = np.mean(revenue)

print('Total revenue = Rs.', total_revenue)
print('Average revenue = Rs.', round(average_revenue, 2))

In [ ]:
# Step 5: Find products with revenue above average
high_revenue_mask = revenue > average_revenue
high_revenue_products = product_names[high_revenue_mask]
high_revenue_values = revenue[high_revenue_mask]

print('Products with above-average revenue:', high_revenue_products)
print('Their revenues:', high_revenue_values)

In [ ]:
# Step 6: Find the top revenue product
top_index = np.argmax(revenue)

print('Top revenue product:', product_names[top_index])
print('Top revenue value: Rs.', revenue[top_index])

### Plain-English Interpretation

The code above helps answer business questions such as:

- How much revenue did each product generate?
- What is the total revenue?
- Which products performed above average?
- Which product generated the highest revenue?


## Final Guided Practice

Ask learners to complete this section independently first. Then reveal/discuss the solution.

### Task
You are given marks of students in three subjects: Python, Math, and Communication.

Find:

1. Average score of each student
2. Average score of each subject
3. Students who passed overall, assuming average >= 50
4. Highest average score


In [ ]:
# Final Practice Data
student_names = np.array(['Asha', 'Rahul', 'Meena', 'Kiran', 'Fatima'])
scores = np.array([
    [72, 80, 75],
    [45, 50, 48],
    [88, 92, 85],
    [60, 55, 58],
    [35, 42, 40]
])

print('Student names:', student_names)
print('Scores:')
print(scores)

In [ ]:
# Solution
student_avg = np.mean(scores, axis=1)
subject_avg = np.mean(scores, axis=0)
passed_students = student_names[student_avg >= 50]
highest_avg = np.max(student_avg)
topper_name = student_names[np.argmax(student_avg)]

print('Average score of each student:')
for name, avg in zip(student_names, student_avg):
    print(name, '=', round(avg, 2))

print('\nAverage score of each subject:')
for subject, avg in zip(['Python', 'Math', 'Communication'], subject_avg):
    print(subject, '=', round(avg, 2))

print('\nStudents who passed overall:', passed_students)
print('Highest average score:', round(highest_avg, 2))
print('Top student:', topper_name)

## Session Wrap-Up

In this notebook, learners practiced the must-have NumPy foundations:

- Creating arrays
- Inspecting array structure
- Indexing and slicing
- Boolean filtering
- Vectorized operations
- Mathematical/statistical summaries
- Reshaping and flattening
- Solving a small practical data problem

These concepts are directly useful before learning Pandas, data analysis, ML preprocessing, and Scikit-learn workflows.
