<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/master/M5C10%20Advanced%20Model%20Selection%20Workshop%20IITR_Optimal_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#A model that performs really well on training data but not good on the test data --> overfitting

In [ ]:
# Parameters to condider while selecting the model:

# 1. Training performance.
# 2. Test performance
# 3. Bias
# 4. Variance
# 5. Generalization
# 6. Computational Cost
# 7. Business requirements

In [ ]:
#Bias: it is the error caused by the model being too simple to understand the underlying pattern in the data

# eg: when the relation between x and y is too complex, but we use a very simple model,
# then the model will not be able to capture this relationship well. This will lead to high bias


# For house price prediction, the different important factors are:
# 1. Area
# 2. Location_rank
# 3. Number of bhk
# 4. Age
# 5. Parking + Aminities


# but if model learns: price = location_rank*200
# too simple model leads to high bias


In [ ]:
# Variance: how much the model's prediction will change when the training data changes

# a high variance model learns the training data very closely --> this leads to overfitting

In [ ]:
# Condition
# 1. Model too simple:
# - high bias
# - low variance
# - Underfitting


# 2. Model is too complex:
# - low bias
# - high variance
# - overfitting

# We prefer a balanced model --> good generalization



In [ ]:
# Underfitting and Overfitting

# 1. Underfitting --> the model is unable to learn the important patterns.

# signs:
# training performance --> poor
# test performance --> poor


# 2. Overfitting: model learns the training data too closely --> poor generalization

# signs:
# training performance --> very good
# test performance --> bad


# Good Fit model: that generalizes well

# signs:
# 1. Training performance: 95% accuracy
# 2. test performance: 92% accuracy



In [ ]:
import numpy as np

a = np.linspace(0,10,6)
print(a)


[ 0.  2.  4.  6.  8. 10.]


In [ ]:
b = np.linspace(0,10,5)
print(b)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#Bias - Variance Tradeoff:

1. very simple model --> high bias
2. increase the complxity --> bias decreases
3. Very complex model --> high variance
4. good fit --> somewhere in between - well balanced:

In [ ]:
#Ensemble Models: Ensemble learning combines multiple models to produce a stronger overall prediction
# numerical data --> average
# categorical data --> majority voting

from sklearn.datasets import load_iris

data = load_iris()

x = data.data
y = data.target


In [ ]:
x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
y[:5]

array([0, 0, 0, 0, 0])

In [ ]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [ ]:
# 1. Logistic Regression
# 2. Decision tree classifier

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

lr = LogisticRegression()
dtc = DecisionTreeClassifier(max_depth = 3, random_state = 42)

In [ ]:
lr.fit(x_train, y_train)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [ ]:
score1 = lr.score(x_test, y_test)
score2 = dtc.score(x_test, y_test)

In [ ]:
score1

1.0

In [ ]:
score2

1.0